name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run macOS tests
      run: xcodebuild test -scheme Components -destination platform="macOS"
    - name: Run iOS tests
      run: xcodebuild test -scheme Components-iOS -destination platform="iOS Simulator,name=iPhone 11 Pro"
